name: scrna-immune-checkpoint-response
channels:
  - conda-forge
  - bioconda
dependencies:
  # R kernel + Jupyter
  - r-base
  - r-irkernel
  - notebook
  - jupyterlab
  # R packages
  - r-seurat=5.4.0 
  - r-harmony
  - bioconda::r-geoquery
  - bioconda::r-glmgampoi
  - r-dplyr
  - r-ggplot2
  - r-future
  - bioconda::r-singler
  - bioconda::r-celldex
  - r-rcolorbrewer
  - r-patchwork
  - pandas
